[package]
name = "db-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
fred.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

redis = { path = "../redis" }
