name: Continuous Deployment (Production)

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push exchange-router images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.router
          push: true
          tags: jogeshwar01/exchange-router:${{ github.sha }}

      - name: Build and push exchange-ws-stream images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.ws-stream
          push: true
          tags: jogeshwar01/exchange-ws-stream:${{ github.sha }}

      - name: Build and push exchange-db-processor images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.db-processor
          push: true
          tags: jogeshwar01/exchange-db-processor:${{ github.sha }}

      - name: Build and push exchange-engine images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.engine
          push: true
          tags: jogeshwar01/exchange-engine:${{ github.sha }}

      - name: Clone exchange-ops repo, update image tags, and push tags
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/jogeshwar01/exchange-ops.git
          cd exchange-ops

          sed -i 's|image: jogeshwar01/exchange-router:.*|image: jogeshwar01/exchange-router:${{ github.sha }}|' backend/deployment.yml
          sed -i 's|image: jogeshwar01/exchange-ws-stream:.*|image: jogeshwar01/exchange-ws-stream:${{ github.sha }}|' websocket/deployment.yml
          sed -i 's|image: jogeshwar01/exchange-db-processor:.*|image: jogeshwar01/exchange-db-processor:${{ github.sha }}|' db-processor/deployment.yml
          sed -i 's|image: jogeshwar01/exchange-engine:.*|image: jogeshwar01/exchange-engine:${{ github.sha }}|' engine/deployment.yml

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "deploy: update exchange image tags to ${{ github.sha }}"
          git push https://${PAT}@github.com/jogeshwar01/exchange-ops.git main
